# Это твоя личная, пополняемая инструкция Python ;)

### Пользуйся ссылками в содержании, чтобы провалиться в нужную тему

# Содержание

#### [1. Стандартные структуры данных](#1.-Стандартные-структуры-данных)
   * [Что умеют все типы данных](#Что-умеют-все-типы)
       * Логика, сравнение (по значению и ID), печать
   * [Численные типы данных](#Что-умеют-численные-типы)
       * Арифметические операции, сравнение, приведение друг к другу, округление, работа в разных системах счисления
   * [Итерируемые типы данных](#Что-умеют-итерируемые-типы)
       * list, dict, set, string, tuple, в общем об итераторах
       * [Упорядоченные типы данных](#Что-умеют-упорядоченные-типы)
           * list, range, tuple, string
           * последовательности, проверка на принадлежность, конкатенация, индексы, слайсы
           * [Изменяемые упорядоченные типы данных](#Что-умеют-изменяемые-упорядоченные-типы)
               * list
               * добавление, удаление, изменение элемента; сортировка in-place, вложенность списков 
       * [Неупорядоченные итерируемые типы данных](#Неупорядоченные-итерируемые-типы)
           * dict, set
           * операции с множествами

#### [2. List Comprehension и другие простые трюки со стандартными типами данных](#2.-List-Comprehension-и-другие-трюки)
   * [Пересечение множеств](#Пересечение-множеств)
   * [Создание словаря "Слово - количество упоминаний в тексте"](#Текст)

#### [3. Функции. Передача аргументов в функцию](#3.-Функции.-Передача-аргументов-в-функцию)
#### [4. Lambda-функции. Map, filter, reduce, sorted](#4.-Lambda-функции.-Map,-filter,-reduce,-sorted)
   * [Функции одной переменной](#Функции-одной-переменной)
       * [List comprehension](#List-comprehension)
       * [Функция map](#Функция-map)
       * [Функция filter](#Функция-filter)
       * [Ключ в sorted](#Ключ-в-sorted)
   * [Функции двух переменных](#Функции-двух-переменных)
       * [Функция reduce](#Функция-reduce)
   * [Лямбды и фабрики функций](#Лямбды-и-фабрики-функций)

#### [5. Работа со словарями](#5.-Работа-со-словарями)
#### [6. Считывание и преобразование данных](#6.-Считывание-и-преобразование-данных)

# 1. Стандартные структуры данных
Это краткий справочник про стандартные структуры данных (data structures) языка Python.

Слово «стандартные» означает, что они входят в стандартную библиотеку языка https://docs.python.org/3/library/, то есть ту, которая загружается по умолчанию каждый раз, когда мы используем язык. Стандартная библиотека поставляется нам, как говорят, «из коробки», то есть включается в базовую комплектацию языка. Не будем пока вникать в то, что такое вообще библиотека, а разберёмся с тем, что в ней лежит.

Стандартные типы в Python иерархичны. Можно представлять себе эту иерархию как дерево. В корне дерева лежат те свойства и операции, которые присущи всем стандартным структурам. Далее происходит деление на две ветви: типы, которые поддерживают и которые не поддерживают итерирование. Типы, которые поддерживают итерирование, делятся на упорядоченные и неупорядоченные. Упорядоченные типы делятся на изменяемые и не изменяемые... И так далее.

В данном разделе рассказано в общем про некоторые свойства типов из разных мест этой иерархии

## Что умеют все типы

#### Логика

Про объект любого типа можно спросить, является он логически истинным или ложным. Использовать это можно в качестве проверки в выражениях if и while.

По умолчанию, все объекты истинны, кроме специально выделенных констант. Для тех типов, для которых имеет смысл понятие их *размера*, объекты нулевого размера равны ложны, а все остальные – истинны.

Так как про любой объект можно спросить, истиннен он или ложен, над объектами любого стандартного типа можно проводить логические операции: and, or и not.

Также существуют логические константы True и False. Внутри они являются целыми числами 1 и 0.

#### Сравнения

Стандартные объекты одного типа можно сравнивать, пользуясь операторами == и !=, is и is not. Первые два проверяют на равенство по значению (при необходимости, приводя типы к одному), а вторые два – на равенство их id.

#### Печать

Любой стандартный тип можно распечатать функцией print или привести его к строке функцией str.


In [20]:
# Проверим некоторые экземпляры объектов на логическую истинность

test_objects = [0.01,
                ["element", 42],
                {"key": "value"},
                [],
                {1, 2, 3},
                "stroka",
                True,
                False,
                None,
                [0, 0],
                (None, None, False)]

for test_object in test_objects:
    if(test_object): # Проверяем на логическую истинность
        print(str(test_object) + u" типа " + str(type(test_object)) + " истиннен")
    else:
        print(str(test_object) + u" типа " + str(type(test_object)) + " ложен")

0.01 типа <class 'float'> истиннен
['element', 42] типа <class 'list'> истиннен
{'key': 'value'} типа <class 'dict'> истиннен
[] типа <class 'list'> ложен
{1, 2, 3} типа <class 'set'> истиннен
stroka типа <class 'str'> истиннен
True типа <class 'bool'> истиннен
False типа <class 'bool'> ложен
None типа <class 'NoneType'> ложен
[0, 0] типа <class 'list'> истиннен
(None, None, False) типа <class 'tuple'> истиннен


In [29]:
# По поводу операторов – чем отличается is от ==?

print(1 == True)
print(1 is True)

# Почему? Потому что хоть у них и равные значения, у них разные id.

one = 1
true = True
one_id = id(one)
true_id = id(true)
print(one_id, true_id)
print(one_id == true_id)

True
False
4456346688 4455943440
False


## Что умеют численные типы

Численные типы – это int, float, complex. Документация со всеми операциями: https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex

Над ними предусмотрены:
1. Арифметические операции (+, %, /, \*, ...)
2. Сравнения (не только == и !=, но и >, <=, ...)
3. Приведение друг к другу.
4. Округление, вычисление длины в разных системах счисления.

Ещё можно приводить числа в разные системы счисления и выполнять над ними логические операции (будет дальше).

In [53]:
# Примеры

integer = 42
real = 42.42
complex_number = complex(42, 0)

# Распечатаем
print("printing")
print(integer, rational, complex_number)

# Выполним над целым числом арифметическую операцию
print("\ninteger arithmetics")
modified_integer = (integer % 5) ** 2 
print(modified_integer)

# Что будет, если мы будем искать остаток от деления для дробного числа?
print("\nreal arithmetics")
modified_real = (real % 5) ** 2
print(modified_real)

# Особая операция для комплексного числа – вычисление сопряженного
print("\ncomplex arithmetics")
nontrivial_complex = complex(2, 1)
conjugated_complex = nontrivial_complex.conjugate()
print(nontrivial_complex, conjugated_complex)
# для комплексоного числа с нулевой комплексной частью оно совпадает со своим сопряженным:
print(complex_number == complex_number.conjugate())



# Сравним целое и целое числа, рациональное и рациональное
print("\none-type comparison")
print(integer >= modified_integer)
print(real < modified_real)

# Если мы попытаемся сравнить целое и рациональное числа между собой, целое приведётся к рациональному, а потом выполнится сравнение
print("\nreal and integer comparison")
print(integer == real)
print(integer < real)

# Сравнение целого и комплексного на равенство
print("\ncomplex and integer equality")
print(integer == complex_number)

printing
42 42.42 (42+0j)

integer arithmetics
4

real arithmetics
5.856400000000008

complex arithmetics
(2+1j) (2-1j)
True

one-type comparison
True
False

real and integer comparison
False
True

complex and integer equality
True


In [51]:
# Но сравнивать комплексные числа операторами "больше" и "меньше" нельзя
print(integer >= complex_number) # Здесь будет сообщение об ошибке. 

TypeError: '>=' not supported between instances of 'int' and 'complex'

In [52]:
# Попробуем тогда привести целое число к комплексному и сравнить его с complex_number
print(complex(integer) >= complex_number) # Снова сообщение об ошибке! 

TypeError: '>=' not supported between instances of 'complex' and 'complex'

In [55]:
# Для рациональных действительных чисел
# (то есть представимых в виде несокращаемой дроби с целым числителем и натуральным знаменателем)
# можно вывести числа, которые при делении дают это рациональное

print(0.5.as_integer_ratio())
print(real.as_integer_ratio())


(1, 2)
(2985042128016507, 70368744177664)


## Что умеют итерируемые типы

Итерируемые типы – это тип структур данных, для которых определены специальные объекты – итераторы. Сюда входят типы list, dict, set, string, tuple.

Выражаясь просто, итератор – это такой объект, который умеет перемещаться по структуре данных последовательно из одного места в другое. Сам по себе итератор умеет выполнять только одно специфическое действие: переходить к следующему элементу. А также, как и любой другой объект, его можно сравнивать с другими итераторами.

Для любого объекта итерируемого типа мы можем запросить его итератор явным образом (см. ниже).
Но мы обычно используем итерируемость неявно, когда, например, "пробегаемся" по списку, словарю, строке или генератору.
Для итерируемых типов существуют те самые list comprehension, dict comprehension и т.п., про которые будет подробно рассказано внизу.

Итерируемые типы бывают двух видов: упорядоченные и неупорядоченные.

In [2]:
# Явная итерация – например, для списка

words = ["one", "two", "three", "four"]
words_iterator = iter(words) # явно запросим итератор для этого списка слов

print(words_iterator) # Итератор указывает на начало списка, до первого элемента

# Шагнем к следующему элементу
print(next(words_iterator)) # Перейдем к следующему элементу – первому

# Проделаем это ещё трижды, пока список не закончится
print(next(words_iterator))
print(next(words_iterator))
print(next(words_iterator))

# Если попробуем шагнуть ещё раз, не получится – список закончился. 
# Получим ошибку StopIteration
print(next(words_iterator))

one
two
three
four


StopIteration: 

In [81]:
# Но вообще мы пользуемся итераторами иначе, а именно:

for word in words: # Внутри цикла for в реальности используются итераторы
    print(word)

one
two
three
four


In [95]:
# Если мы хотим также знать индексы элементов, по которым мы итерируемся,
# мы можем использовать функцию enumerate.
# Она возвращает генератор пар вида (индекс, элемент)

for index, word in enumerate(words):
    print(index, word)

0 one
1 two
2 three
3 four


In [3]:
# Для словарей мы можем итерироваться по всем ключам

impression_dict = {
    "погода": "дождь и туман",
    "настроение" : "сплин",
    "город" : "Лондон"
}

for key in impression_dict:
    print(key)

погода
настроение
город


In [4]:
# А можем по паре (ключ, значение), используя метод items, которая возвращает генератор таких пар

for key, value in impression_dict.items():
    print(key, " сегодня – ", value)

погода  сегодня –  дождь и туман
настроение  сегодня –  сплин
город  сегодня –  Лондон


In [98]:
# Что будет, если мы попробуем поитерироваться по неитерируемым типам – числовым?
# Будет ошибка: этот тип не итерируемый

for digit in 12345:
    print(digit)

TypeError: 'int' object is not iterable

## Что умеют упорядоченные типы

Упорядоченные (sequential) типы – это такие типы, которые состоят из упорядоченной последовательности элементов.
У них есть начало и конец, они знают, сколько в них лежит элементов и какого они типа. Пробежаться по ним можно не только по итератору, но и по индексу, потому что они упорядочены и у каждого их элемента есть номер.

Сюда входят: list, range, tuple, string. Ещё входит специальный тип для двоичных данных, но нам он не понадобится.
Упорядоченные типы бывают изменяемые и неизменяемые (уже обсуждали, что это значит).

Полная документация: https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range

In [105]:
# Пример последовательности – строка

subjectStr = u"старый солдат "
verbStr = u"пьёт "
objectStr = u"чай"

# Конкатенация (сложение) последовательностей
text = subjectStr + verbStr + objectStr
print(text)

# Умножение последовательности на целое число
verbStr = verbStr * 5
text = subjectStr + verbStr + objectStr
print(text)

старый солдат пьёт чай
старый солдат пьёт пьёт пьёт пьёт пьёт чай


In [106]:
# Проверка на принадлежность
print(u"а" in text) # элемента
print(u"ю" in text)
print(u"чай" in text) # последовательности элементов
print(u"кофе" in text) 

True
False
True
False


In [114]:
# Взятие элемента по индексу

print(text[16])

# Слайсы

print(text[14:-4])

# Количество вхождений элемента или подпоследовательности в последовательность
print(text.count(u"пьёт"))
print(text.count(u"ест"))

# Поиск индекса первого вхождения элемента или подпоследовательности в последовательность
print(text.index(u"ё"))
print(text.index(u"ю")) # выдаст ошибку, прочитай её

ё
пьёт пьёт пьёт пьёт пьёт
5
0
16


ValueError: substring not found

In [117]:
# Поиск длины, минимума и максимума последовательности

print(len(text))

# Для строк минимумы и максимумы вычисляются по кодировкам символов
print("\"" + min(text) + "\"")
print("\"" + max(text) + "\"")

42
" "
"ё"


## Что умеют изменяемые упорядоченные типы

Изменяемый последовательный тип – это list.
Помимо всего того, что можно делать со строками и кортежами, в list можно влезть по индексу, элементу или итератору и что-нибудь там изменить.

In [148]:
# Примеры. Проследим, что id объекта не изменится.

words = ["one", "two", "three", "four", "five"]
words_id = id(words)

# Добавим элемент в конец
words.append("six")
print(words)

# Удалим элемент в конце
lastWord = words.pop()
print(lastWord)
print(words)

# Заменим элемент
words[0] = "cat"
print(words)
# И целую подпоследовательность
words[1:5] = ["dog", "giraffe", "badger"]
print(words)

# Удалим элемент по индексу
del words[1]
print(words)

# Или по элементу
words.remove("cat")
print(words)

# Отсортируем список in-place (то есть не создавая дополнительных объектов)
words.sort()
print(words)

# Очистим список
words.clear()
print(words)

# Что там с id?
words_id == id(words)

['one', 'two', 'three', 'four', 'five', 'six']
six
['one', 'two', 'three', 'four', 'five']
['cat', 'two', 'three', 'four', 'five']
['cat', 'dog', 'giraffe', 'badger']
['cat', 'giraffe', 'badger']
['giraffe', 'badger']
['badger', 'giraffe']
[]


True

In [152]:
# Списки (как и словари и кортежи) поддерживают вложенность

nested_list = [
    [
        [0, 1, 2],
        [3, 4, 5]
    ],
    [
        [6, 7, 8],
        [9, 10, 11]
    ]
]

# Обращаться к ним не страшно:

print(nested_list[0])
print(nested_list[0][0])
print(nested_list[0][0][0])

[[0, 1, 2], [3, 4, 5]]
[0, 1, 2]
0


In [157]:
# С элементами вложенного списка мы работаем, как обычно:

print(nested_list[1][1])
print(min(nested_list[1][1]))
nested_list[1][1].reverse()
print(nested_list[1][1])

[9, 10, 11]
9
[11, 10, 9]


## Неупорядоченные итерируемые типы

Здесь нас интересуют dict и set, словарь и множество. Они не являются последовательными, потому что на элементах словаря и множества нет явного порядка, нам не важно, кто из них первый, кто последний.

Словарь, dict, в некотором смысле проиндексирован своими ключами. В множестве индексы отсутствуют совсем.

Множества – это множества в математическом смысле. Над ними можно проводить все теоретико-множественные операции.
Словарь лучше всего представлять себе как реальный словарь, в котором есть слова и словарные статьи.

In [170]:
# Операции над set

zoo = {"cat", "dog", "bird"}
farm = {"dog", "cow"}
house = {"cat"}

# Добавить новый элемент
zoo.add("snake") # add, а не append, потому что не в конец, а вообще
print(zoo)

# Добавить элемент, который уже был – множество не изменится
zoo.add("cat") 
print(zoo)

# Проверка на принадлежность
print("elephant" in zoo)

{'cat', 'snake', 'bird', 'dog'}
{'cat', 'snake', 'bird', 'dog'}
False


In [165]:
# Сравнить множества
print(zoo > house) # верно ли, что house содержится в zoo?
print(zoo > farm)

True
False


In [169]:
# Найти пересечение множеств
print(zoo.intersection(farm))

# Найти дополнение к множеству в другом множестве
print(zoo.difference(farm))

# Объединить множества
animals = zoo.union(farm)
print(animals)

# Вычесть одно множество из другого
print(animals - house)

{'dog'}
{'cat', 'snake', 'bird'}
{'snake', 'cow', 'cat', 'bird', 'dog'}
{'bird', 'snake', 'cow', 'dog'}


# 2. List Comprehension и другие трюки

In [1]:
squares = [number ** 2 for number in range(11)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


Создать список длин слов из предложения `sentence`, но только не артиклей.

Подсказка: посмотреть документацию для метода `split` для строк (strings).

In [6]:
sentence = "a quick brown fox jumps over the lazy dog"
# Решение:
articles = ("a", "the")
words = sentence.split()
length = []
[length.append(len(element)) for element in words if element not in articles]
print(lens)
#for element in words:
#    if element not in articles:
#        lens.append(len(element))
#        print(element, len(element)) # для явного просмотра :)
#print(lens)

[5, 5, 3, 5, 4, 4, 3]


Создать и вывести список `natural_numbers`, который будет содержать только положительные числа из `real_numbers`, причём округлить эти числа до целых вверх.

Подсказка: посмотреть документацию по функциям `floor` и `ceil` из библиотеки `math`. Чем они отличаются от функции `int` в стандартной библиотеке?

In [8]:
import math # импортируем библиотеку math, в которой есть функции для округления чисел
real_numbers = [34.6, -203.4, 44.9, 68.3, -12.2, 44.6, 12.7]

# Решение:
natural_numbers = [math.ceil(number) for number in real_numbers if number > 0]
print(natural_numbers)

[35, 45, 69, 45, 13]


Создать и вывести список всех целых чисел от 1 до 1000, которые делятся на 7. 

In [7]:
divided_by_seven = [number for number in range(1,15) if number % 7 == 0]
print(divided_by_seven)

[7, 14]


Создать и вывести список всех целых чисел от 1 до 1000, которые содержат в своей записи тройку.

Подсказка: чтобы смотреть на отдельные цифры какого-то числа, к нему нужно относиться, как к строке, или – ещё удобней – как к списку символов этой строки.

In [6]:
for number in range(1,14):
    if "3" in set(str(number)):
        print(number, end = " ")

3 13 

Создать список списков, в котором элемент с номером `i` будет списком чисел от 1 до n, которые делятся на `i`.

Пусть `i` от 2 до 100.

In [9]:
# Финальный список будет выглядеть как-то так:
# divisible_by_index = [[2, 4, 6, 8, ..., 100], [3, 6, 9, ..., 99], ..., [100]]
[[number for number in range(2,10) if (number % divisor == 0)] for divisor in range(2,10)]

[[2, 4, 6, 8], [3, 6, 9], [4, 8], [5], [6], [7], [8], [9]]

*List comprehension* можно использовать также и для словарей (`dict`). Выполнить предыдущее со словарём вместо списка списков так, чтобы в получившемся словаре лежали пары вида `i: [числа от 1 до 100, которые делятся на i]`. Снова `i` от 2 до 100.

In [ ]:
# Формат ответа
# divisible_by_index = {2 : [2, 4, ..., 100], 3 : [3, 6, ..., 99], ..., 100 : [100]}

Создать список `[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]`.

In [32]:
[-(10 - i) for i in range(11)]

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

### Пересечение множеств

Для двух списков вывести те элементы, которые содержатся в обоих.
Выполнить задание тремя способами:

1) c помощью list comprehension;

2) с помощью set.

In [10]:
first = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
second = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

#1)
[print(first[i]) for i in range(len(first)) if first[i] in second]

#2)
set(first).intersection(set(second))

1
1
2
3
5
8
13


{1, 2, 3, 5, 8, 13}

### Текст

Для текста `text` (сгенерирован случайно) посчитать, сколько раз каждое слово в него входит.

Считаем, что словами не считаются пробелы и знаки препинания, а также что «слово», «Слово» и «СЛОВО» -- одинаковые элементы.

Обратите внимание на методы и функции: `replace`, `lower`, `split`.

In [57]:
text = "Do in laughter securing smallest sensible no mr hastened. As perhaps proceed in in brandon of limited unknown greatly. Distrusts fulfilled happiness unwilling as explained of difficult. No landlord of peculiar ladyship attended if contempt ecstatic. Loud wish made on is am as hard. Court so avoid in plate hence. Of received mr breeding concerns peculiar securing landlord. Spot to many it four bred soon well to. Or am promotion in no departure abilities. Whatever landlord yourself at by pleasure of children be. "

In [65]:
frequency_dictionary = {}
text = text.replace('.', '')
words = [word.lower() for word in text.split()]
for word in words:
    frequency_dictionary[word] = frequency_dictionary.get(word, 0) + 1
print(frequency_dictionary)

{'do': 1, 'in': 5, 'laughter': 1, 'securing': 2, 'smallest': 1, 'sensible': 1, 'no': 3, 'mr': 2, 'hastened': 1, 'as': 3, 'perhaps': 1, 'proceed': 1, 'brandon': 1, 'of': 5, 'limited': 1, 'unknown': 1, 'greatly': 1, 'distrusts': 1, 'fulfilled': 1, 'happiness': 1, 'unwilling': 1, 'explained': 1, 'difficult': 1, 'landlord': 3, 'peculiar': 2, 'ladyship': 1, 'attended': 1, 'if': 1, 'contempt': 1, 'ecstatic': 1, 'loud': 1, 'wish': 1, 'made': 1, 'on': 1, 'is': 1, 'am': 2, 'hard': 1, 'court': 1, 'so': 1, 'avoid': 1, 'plate': 1, 'hence': 1, 'received': 1, 'breeding': 1, 'concerns': 1, 'spot': 1, 'to': 2, 'many': 1, 'it': 1, 'four': 1, 'bred': 1, 'soon': 1, 'well': 1, 'or': 1, 'promotion': 1, 'departure': 1, 'abilities': 1, 'whatever': 1, 'yourself': 1, 'at': 1, 'by': 1, 'pleasure': 1, 'children': 1, 'be': 1}


### И ещё раз про списки.

Написать функцию, которая сортирует (вручную, без использования стандартных функций) список `numbers`. Сортировка должна происходить *in place*, то есть дополнительный список заводить нельзя.

Протестировать функцию следующим образом: создать несколько примеров списков, постаравшись включить как случайный общий, также и граничные случаи, и проверить, что самописная функция выдаёт тот же ответ, что и стандартная функция `sorted()`.

In [5]:
numbers_1 = [3, 1, 0, -5, 12, -1, 5]

def my_sort(numbers):
    for element in range(1,len(numbers)):
        for k in range(len(numbers) - element):
            if numbers[k] > numbers[k+1]:
                numbers[k], numbers[k+1] = numbers[k+1], numbers[k]
    return(numbers)

In [8]:
result = my_sort(numbers_1)
check = sorted(numbers_1)

In [9]:
print(result)
print(check)

[-5, -1, 0, 1, 3, 5, 12]
[-5, -1, 0, 1, 3, 5, 12]


# 3. Функции. Передача аргументов в функцию
Делается ли это `by reference` или `by value`

In [1]:
# Вспомогательная функция
import inspect

def this_function_name():
    return(inspect.stack()[1].function) # 1, а не 0, т.к. нужен caller

In [7]:
def any_function():
    return inspect.stack()[0].function
    
any_function()

'any_function'

In [2]:
# О стеках
stack = [1, 2, 42]
# push
stack.append(0)
print(stack)
# pop
last = stack.pop() # Пример функции, которая делает два дела
print(stack)

[1, 2, 42, 0]
[1, 2, 42]


In [3]:
def change_integer(arg):
    arg = 42
    print('{}: argument is now set to {}'.format(this_function_name(), arg))

In [4]:
x = 10
change_integer(x)
print(x)

change_integer: argument is now set to 42
10


In [5]:
def change_list(arg):
    arg = [1, 2, 3]
    print('{}: argument is now set to {}'.format(this_function_name(), arg))

In [6]:
x = []
change_list(x)
print(x)

change_list: argument is now set to [1, 2, 3]
[]


In [7]:
def change_list_elements(arg):
    arg.append(42)
    print('{}: argument is now set to {}'.format(this_function_name(), arg))

In [8]:
x = []
change_list_elements(x)
print(x)

change_list_elements: argument is now set to [42]
[42]


In [9]:
# Как поменять что-то?
# Как надо: вынести изменение из функции
def get_new_value(arg):
    return(arg + 1)

In [10]:
x = 42
x = get_new_value(42)
print(x)

43


In [16]:
# Как НЕ НАДО: с помощью глобальных переменных
# О них

arg = 1 # <-- глобальная переменная
print('{}: argument is now set to {}'.format(this_function_name(), arg)) 

def f():
    # Единственная известная нам arg -- глобальная, ее можно прочитать
    print('{}: argument is now set to {}'.format(this_function_name(), arg))
    
f()

<module>: argument is now set to 1
f: argument is now set to 1


In [17]:
# Выдаёт ошибку
def f_faulty():
    arg = arg + 1 # <-- правая часть (чтение) сработает, а assignment нет
    print('{}: argument is now set to {}'.format(this_function_name(), arg))
    
f_faulty()

UnboundLocalError: local variable 'arg' referenced before assignment

In [18]:
def g():
    arg = 2 # <-- создает локальную с тем же именем
    print('{}: argument is now set to {}'.format(this_function_name(), arg)) 

def h(): 
    global arg 
    arg = 3
    print('{}: argument is now set to {}'.format(this_function_name(), arg)) 
    
f()
print('{}: argument is now set to {}'.format(this_function_name(), arg)) 
g()
print('{}: argument is now set to {}'.format(this_function_name(), arg)) 
h()
print('{}: argument is now set to {}'.format(this_function_name(), arg)) 

f: argument is now set to 1
<module>: argument is now set to 1
g: argument is now set to 2
<module>: argument is now set to 1
h: argument is now set to 3
<module>: argument is now set to 3


In [19]:
# Итак, как не надо
def get_new_value_WRONG():
    global arg
    arg = 'Seriuosly, don\'t'
    
arg = 'Don\'t use global variables'
print(arg)
get_new_value_WRONG()
print(arg)

Don't use global variables
Seriuosly, don't


In [20]:
# Если несколько аргументов?
def get_new_values(text, number):
    new_text = text + "!!!"
    new_number = number + 1
    return(new_text, new_number)

In [21]:
x, y = "some text", 42
x, y = get_new_values(x, y)
print(x, y)

some text!!! 43


# 4. Lambda-функции. Map, filter, reduce, sorted

### Функции одной переменной

#### List comprehension

In [4]:
numbers = [1, 2, 3, 4]

def square(x):
    return x ** 2

[square(x) for x in numbers]

[1, 4, 9, 16]

In [23]:
lambda_square = lambda x : x ** 2

[lambda_square(x) for x in numbers]

[1, 4, 9, 16]

In [24]:
# И даже
[(lambda x: x ** 2)(x) for x in numbers]

[1, 4, 9, 16]

#### Функция map

In [25]:
list(map(square, numbers))

[1, 4, 9, 16]

In [26]:
# Как устроена map?

def my_map(function, iterable):
    # но оптимизирована
    for item in iterable:
        yield function(item)
        
list(my_map(square, numbers))

[1, 4, 9, 16]

In [27]:
# А что с лямбдами

list(map(lambda x: x ** 2, numbers))

[1, 4, 9, 16]

In [1]:
digits = [1, 2, 3, 4, 6]
digits_str = list(map(str, digits))
"".join(digits_str)

'12346'

In [3]:
# Аналог в numpy
# elementwise operation

import numpy as np
a = np.array(numbers)
a ** 2

array([ 4,  4,  9, 16], dtype=int32)

In [16]:
# Если размерность больше и любая функция
matrix = np.arange(1, 17).reshape(2, 2, 2, 2)
print(matrix)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


In [17]:
np.apply_along_axis(lambda x: x ** 2, 1, matrix)

array([[[[  1,   4],
         [  9,  16]],

        [[ 25,  36],
         [ 49,  64]]],


       [[[ 81, 100],
         [121, 144]],

        [[169, 196],
         [225, 256]]]])

In [20]:
# На этом примере видно, к чему применилась лямбда
np.apply_along_axis(lambda x: x[0], 2, matrix)

array([[[ 1,  2],
        [ 5,  6]],

       [[ 9, 10],
        [13, 14]]])

#### Функция filter

In [30]:
[x for x in numbers if x % 2 == 0]

[2, 4]

In [21]:
[x if x % 2 else x - 1 for x in numbers]

[1, 1, 3, 3]

In [33]:
list(filter(lambda x: x % 2 == 0, numbers))

[2, 4]

In [25]:
list(filter(lambda x: x, numbers))

[1, 2, 3, 4]

#### Ключ в sorted

In [34]:
c_numbers = [
    complex(1, 1),
    complex(2, 3),
    complex(3, 2),
    ]

sorted(c_numbers)

TypeError: '<' not supported between instances of 'complex' and 'complex'

In [39]:
sorted(c_numbers, key=lambda x: x.real)

[(1+1j), (2+3j), (3+2j)]

In [40]:
sorted(c_numbers, key=lambda x: x.imag)

[(1+1j), (3+2j), (2+3j)]

### Функции двух переменных

In [0]:
lambda x, y: x + y ** 2

#### Функция reduce

In [7]:
from functools import reduce 

numbers = [3, 2, 3, 4]

# Как сделать сумму квадратов?

reduce(lambda x, y: x + y ** 2, numbers)

32

In [8]:
# Аналог в numpy

a = np.array(numbers)
np.add.reduce(a ** 2)

38

Вообще это работает только с `numpy` объектами `ufunc` (universal functions), их много, список
[здесь](https://docs.scipy.org/doc/numpy/reference/ufuncs.html).

Но мы можем создать такой объект из любой питоновской функции.

In [57]:
add_squares = np.frompyfunc(lambda x, y: x + y ** 2, 2, 1)
add_squares.reduce(a)

30

### Лямбды и фабрики функций

In [58]:
def multiply_by_n_factory(n):
    return lambda x: x * n

double = multiply_by_n_factory(2)
triple = multiply_by_n_factory(3)
quadriple = multiply_by_n_factory(4)

double(10)

20

In [59]:
triple(10)

30

In [60]:
quadriple(10)

40

# 5. Работа со словарями

### Инвентарь
 
Произвести операции над словарем, который описывает имущество персонажа игры.

In [31]:
inventory = {
    'gold' : 500,
    'pouch' : ['flint', 'twine', 'gemstone'],
    'backpack' : ['xylophone','dagger', 'bedroll','bread loaf']
}

Добавить в словарь ключ `'pocket'`.

In [10]:
inventory['pocket'] = []  

Положить в `'pocket'` список вещей, то есть строк: `'seashell'`, `'strange berry'` и `'lint'`.

In [11]:
inventory['pocket'] = ['seashell', 'strange berry', 'lint']

Отсортировать элементы в рюкзаке `'backpack'`.


In [12]:
sorted(inventory['backpack'])

['bedroll', 'bread loaf', 'dagger', 'xylophone']

Удалить ножик `'dagger'`.


In [13]:
inventory['backpack'].remove('dagger')
print(inventory['backpack'])

['xylophone', 'bedroll', 'bread loaf']


Добавить 50 золота в кошелек `'gold'`.

In [55]:
inventory['gold'] += 50
print(inventory['gold'])

550


### Фруктовая лавка

Создать словарь `prices`, в котором будут лежать такие элементы:

`"banana": 4,
"apple": 2,
"orange": 1.5,
"pear": 3`

А также словарь `stock`, в котором будет лежать количество фруктов каждого типа:

`"banana": 6,
"apple": 0,
"orange": 32,
"pear": 15`

In [16]:
fruits = ['banana', 'apple', 'orange', 'pear']
costs = [4, 2, 1.5, 3]
amounts = [6, 0, 32, 15]

prices = dict(zip(fruits, costs))
stock = dict(zip(fruits, amounts))

print(prices)

{'banana': 4, 'apple': 2, 'orange': 1.5, 'pear': 3}


Пробежаться по всем фруктам и для каждого вывести информацию в виде:

`apple
price: 2
stock: 0`

In [26]:
for fruit in fruits:
    print(fruit, '\n price:', prices[fruit], '\n stock:', stock[fruit])

banana 
 price: 4 
 stock: 6
apple 
 price: 2 
 stock: 0
orange 
 price: 1.5 
 stock: 32
pear 
 price: 3 
 stock: 15


Посчитать, сколько можно получить всего выручки, если продать все имеющиеся фрукты по указанной цене: то есть сложить суммы, полученные как произведение количества фруктов на их цену.

In [28]:
profit = 0
for fruit in fruits:
    profit += prices[fruit]*stock[fruit]
print(profit)

117.0


# 6. Считывание и преобразование данных

#### Считать пару-тройку чисел, разделенны пробелами

In [ ]:
x, y = map(int, input().split())

#### Ввод-вывод одномерного массива

In [ ]:
# первый способ
a = input().split()  # считали строку и разбили ее по пробелам
                     # получился уже массив, но питон пока не понимает, что в массиве числа
for i in range(len(a)):
    a[i] = int(a[i])  # прошли по всем элементам массива и превратили их в числа
    
# второй способ
a = list(map(int, input().split()))

Еще бывает, что числа для массива задаются по одному в строке. Тогда вам проще всего заранее знать, сколько будет вводиться чисел. Обычно как раз так данные и даются: сначала количество элементов, потом сами элементы. Тогда все вводится легко:

In [ ]:
n = int(input())
a = []  # пустой массив, т.е. массив длины 0
for i in range(n):
    a.append(int(input()))  # считали число и сразу добавили в конец массива

Как выводить массив?

In [ ]:
# Если надо по одному числу в строку, то просто:
for i in range(len(a)):
    print(a[i])
    
# Если же надо все числа в одну строку, то есть два способа. 
# Во-первых, можно команде print передать специальный параметр end=" ", 
# который обозначает "заканчивать вывод пробелом (а не переводом строки)":

for i in range(len(a)):
    print(a[i], end=" ")

# Есть другой, более простой способ:

print(*a)

# Эта магия обозначает вот что: возьми все элементы массива a и передай их отдельными аргументами в одну команду print. 
# Т.е. получается print(a[0], a[1], a[2], ...).

#### Ввод-вывод двумерного массива

Обычно двумерный массив вам задается как n строк по m чисел в каждой, причем числа n и m вам задаются заранее. Такой двумерный массив вводится эдакой комбинацией двух способов ввода одномерного массива.

In [ ]:
n, m = map(int, input().split())  # считали n и m из одной строки
# m дальше не будет нужно
a = []
for i in range(n):
    a.append(list(map(int, input().split())))

# либо без map
n = int(input()) 
a = []
for i in range(n):
    a.append([int(j) for j in input().split()])
    
# либо работая с элементами
n = int(input()) 
a = []
for i in range(n):
    row = input().split()
    for i in range(len(row)):
        row[i] = int(row[i])
    a.append(row)
    
# либо с помощью генератора
n = int(input()) 
a = [[int(j) for j in input().split()] for i in range(n)]

Вывод двумерного массива, если вам его надо вывести такой же табличкой, тоже делается комбинацией способов вывода одномерного массива

In [ ]:
for i in range(len(a)):
    print(*a[i])
    
# или так

for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j], end=" ")
    print()  # сделать перевод строки